"use client";

export { StarterKit } from "@tiptap/starter-kit";
export { Highlight } from "@tiptap/extension-highlight";
export { CharacterCount } from "@tiptap/extension-character-count";
export { Underline } from "@tiptap/extension-underline";
export { Placeholder } from "@tiptap/extension-placeholder";
export { TextAlign } from "@tiptap/extension-text-align";
export { TextStyle } from "@tiptap/extension-text-style";
export { FontFamily } from "@tiptap/extension-font-family";
export { Typography } from "@tiptap/extension-typography";
export { Color } from "@tiptap/extension-color";
export { FocusClasses as Focus } from "@tiptap/extension-focus";
export { Dropcursor } from "@tiptap/extension-dropcursor";
export { CollaborationCursor } from "@tiptap/extension-collaboration-cursor";
export { Subscript } from "@tiptap/extension-subscript";
export { Superscript } from "@tiptap/extension-superscript";
export { Paragraph } from "@tiptap/extension-paragraph";
export { BulletList } from "@tiptap/extension-bullet-list";
export { OrderedList } from "@tiptap/extension-ordered-list";
export { Collaboration } from "@tiptap/extension-collaboration";
export { TaskItem } from "@tiptap/extension-task-item";
export { TaskList } from "@tiptap/extension-task-list";

export { Selection } from "./selection";
export { Table, TableCell, TableHeader, TableRow } from "./table";
export { Horizontal } from "./horizontal";
export { Heading } from "./heading";
export { CodeBlock } from "./code-block";
export { Document } from "./document";
export { TrailingNode } from "./trailing-node";
export { SlashCommand } from "./slash-command";
export { FontSize } from "./font-size";
export { Figure } from "./figure";
export { Figcaption } from "./figcaption";
export { Blockquote } from "./blockquote";
export { Quote } from "./quote";
export { QuoteCaption } from "./quote-caption";
export { Link } from "./link";
export { ImageUpload } from "./image-upload";
export { ImageBlock } from "./image-block";
export { Columns, Column } from "./multi-column";
// export { TableOfContents } from './table-contents'
