import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Toaster } from "react-hot-toast";

import { TRPCReactProvider } from "~/trpc/react";

import ThemeProvider from "~/components/common/theme-provider";
import { ScrollArea } from "~/components/ui/scroll-area";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={GeistSans.variable}>
      <body>
        <ScrollArea className="h-screen">
          <TRPCReactProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </TRPCReactProvider>
          <Toaster />
        </ScrollArea>
      </body>
    </html>
  );
}
