import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import { TRPCReactProvider } from "~/trpc/react";

import ThemeProvider from "~/components/common/theme-provider";
import { ScrollArea } from "~/components/ui/scroll-area";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} className={GeistSans.variable}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <ScrollArea className="h-screen">
            <TRPCReactProvider>
              <ThemeProvider>{children}</ThemeProvider>
            </TRPCReactProvider>
            <Toaster />
          </ScrollArea>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
